 
.TH internsctl 1
.SH NAME
internsctl
.SH SYNOPSIS
internsctl [option]... [File]
.SH DESCRIPTION
internsctl is a custom command
.SH OPTION
.IP -a
do not ignore entries starting with .
.IP -f
do not list implied . and ..
.IP --author
with -l, Print the author of the each file
.SH AUTHOR
Subham Das

